### ISSUE TITLE
gulp-rigger or etc.

### ISSUE THREAD

**Issue by ramax495** [wapbamboogie/bootstrap-4-boilerplate#10]
Could you include in your gulp config "gulp-rigger" plugin or etc ?

**Comment by henrikhb** [comment]
You could install it with npm and add it to the dependencies in the top of gulpfile.js like the example on [gulp-rigger](https://www.npmjs.com/package/gulp-rigger)
Then you would need to add it to one of the tasks. Maybe you could add it to the "minifyScripts" task like so: 
`gulp.task("minifyScripts", ["concatScripts"], function() {
  return gulp.src("assets/js/main.js")
    .pipe(uglify())
    .pipe(rigger())
    .pipe(rename('main.min.js'))
    .pipe(gulp.dest('dist/assets/js'));
});`
I have not tried gulp-rigger but that is how I would go about it.
