### ISSUE TITLE
Do you think this library should also support a transpiler?

### ISSUE THREAD

**Issue by aligajani** [wapbamboogie/bootstrap-4-boilerplate#11]

**Comment by henrikhb** [comment]
I think that actually would be great if you're writing es6+ thinking maybe [gulp-babel](https://www.npmjs.com/package/gulp-babel) could be the best option

**Comment by Sylk** [comment]
Close this.

**Comment by aligajani** [comment]
I have integrated ES6 into this package. Will submit pull request soon.
