### ISSUE TITLE
How to include fontawesome 5?

### ISSUE THREAD

**Issue by lordcameltoe** [wapbamboogie/bootstrap-4-boilerplate#13]
I've been trying to add fontawesome 5 to the template. I've followed the instructions here: https://fontawesome.com/how-to-use/web-fonts-with-css#basic-use and it works well when testing using `gulp serve`.

However, when creating an output with just `gulp`, font awesome doesn't load.

Here is what I've done:

1 - Added a folder called "fontawesome" containing all .scss files under the assets/css/2-plugins directory

2 - added `@import 'fontawesome/fontawesome';` into the index.scss file of the plugins directory

3 - added the "webfonts" directory under the "assets" directory

4 - Changed line 11 of the _variables.css file under the css/3-base directory to:
`$path-fonts     :  $fa-font-path;`

Any clues what I'm missing?

**Comment by henrikhb** [comment]
Hi! Sorry for the late reply.

If you added a new directory called "webfonts" in the assets folder you have to make sure that the gulp build command also graps this folder and put it into the dist directory. 

Check line 79 in gulpfile.js. You could add a new folder (webfonts) to the build array like so:

`gulp.task("build", ['minifyScripts', 'minifyCss'], function() {
  return gulp.src(['*.html', '*.php', 'favicon.ico',
                   "assets/img/**", "assets/fonts/**", , "assets/webfonts/**"], { base: './'})
            .pipe(gulp.dest('dist'));
});`

**Comment by Sylk** [comment]
Close this.
