### ISSUE TITLE
gulp serve dont work

### ISSUE THREAD

**Issue by nachoumaran** [wapbamboogie/bootstrap-4-boilerplate#14]
the console give this error:

gulp serve[25492]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x480a030427d
Abort trap: 6

**Comment by henrikhb** [comment]
Try removing node modules and reinstall them

**Comment by nachoumaran** [comment]
still giving the same error, another option?

**Comment by henrikhb** [comment]
Check if you're running the latest stable node version and update if not, you can also try and update gulp or reinstall it globally `npm install -g gulp`, it seems to be a node error so that's all I can really suggest

**Comment by nachoumaran** [comment]
I tried it from a clean installation on a mac and it gave me the same
error, it's not a node problem

**Comment by henrikhb** [comment]
Just fetched the repo and tested on my mac, no errors.

My mac version: 10.13.4
My node version: v. 9.11.1
My global gulp version: 6.1.0

What version of Node are you running?

**Comment by nachoumaran** [comment]
My mac version: 10.13.5
My node version: v10.4.0
My global gulp version: CLI version 3.9.1

**Comment by henrikhb** [comment]
Could be something with the node version, being newer than mine. 
You can try and update all the dependencies in the repo to latest version and see if it solves the issue.
