### ISSUE TITLE
Gulp build task creates minified versions of js and css, but they are mislinked in the html

### ISSUE THREAD

**Issue by citizenbob** [wapbamboogie/bootstrap-4-boilerplate#15]
After uploading the contents of the `dist` folder to a web server, `index.html` is logging 404's in the console. It's looking for `assets/css/main.css` and `assets/js/main.js` instead of what exists (`assets/css/main.min.css` and `assets/js/main.min.js`).

**Comment by henrikhb** [comment]
Hi @bduebel, I can't reproduce this error. 
Could it be that you either uploaded the HTML files from outside the dist directory, or maybe you removed the `<!-- build:js --> <script src="assets/js/main.js"></script> <!-- endbuild -->`  HTML comments that instructs gulp what assets to rename?
