### ISSUE TITLE
tweak to get sourcemaps showing

### ISSUE THREAD

**Issue by nigelwhite** [wapbamboogie/bootstrap-4-boilerplate#17]
Fantastic work!

To get sourcemaps showing up in Dev Tools I had to add
/*# sourceMappingURL=style.css.map */
to the bottom of assets/css/main.scss

Hope this helps someone...

**Comment by nigelwhite** [comment]
Oh no, you've already done that! It's already in main.css.
I guess my browser was slow to get started on the sourcemaps.

However, most (not all) of the soucemaps in dev tools point to _reboot.scss when actually the style is defined elsewhere in the scss structure.
Thanks

**Comment by henrikhb** [comment]
I actually see the same issue, a lot of the styles points to a wrong sass file according to the sourcemap in dev tools and yes usually its _reboot.scss.
I tried changing line 39 in gulpfile.js from `.pipe(sass().on('error', sass.logError))` to `.pipe(sass({ outputStyle: 'compressed'}))` , which seems to work for some reason. Could you try the same and make some scss changes and see if it works for you as well?

**Comment by nigelwhite** [comment]
Hi Henrik.
Maybe its a bit better than it was.... but still lots of _reboot.scss. Sometimes duplicate entries from _reboot.scss.
A great resource all the same. It has got me working in a bootstrap 4 site, so many thanks.
