### ISSUE TITLE
How to include third party css/js/images plugin?

### ISSUE THREAD

**Issue by brunorios1** [wapbamboogie/bootstrap-4-boilerplate#20]
What is the correct way to include a third-party plugin ([bxslider-4](https://github.com/stevenwanderski/bxslider-4)) that has images, css and js and make it work with gulp serve and build?

Thanks!

**Comment by henrikhb** [comment]
Download the needed JS files to your project and add them in the concatScripts task in gulpfile.js. You can also download the CSS and change it to a SCSS file and include it like any other SCSS file.
