### ISSUE TITLE
Vulnerabilitites after npm install

### ISSUE THREAD

**Issue by crashbdx** [wapbamboogie/bootstrap-4-boilerplate#21]
Hi, i get the following message in the terminal after doing npm install:

found 24 vulnerabilities (7 low, 13 moderate, 4 high) in 1941 scanned packages

Is it normal ? can i fix it ?

Thank you in advance.

**Comment by lucazambon** [comment]
This is a problem of npm, not of the repo. Try to run `npm audit fix` to fix it.

**Comment by crashbdx** [comment]
Will do thanks for the help :)

**Comment by henrikhb** [comment]
Hi there! I just ran `npm audit fix` in the repo as wel. It fixed all the vulnerabilities that could be fixed without breaking functionality. So some of the npm packages have been updated if you fetch the latest package.json.

**Comment by lucazambon** [comment]
It doesn’t matter because we will run npm install on installation. And node_modules is ignored by .gitignore and it’s correct like that.
Anyone should run npm audit fix on their machine.

**Comment by henrikhb** [comment]
Well yes the node_modules directory is ignored, however package.json specifies which npm packages to install. So the next person using this repo will not get all of the security warnings, since I pushed the updated package.json file after running `npm audit fix`.

**Comment by lucazambon** [comment]
Oh fine! Nice
