### ISSUE TITLE
HTML main.css/main.js aren't replaced with .min during build?

### ISSUE THREAD

**Issue by aligajani** [wapbamboogie/bootstrap-4-boilerplate#8]

**Comment by henrikhb** [comment]
Seemed to work fine in my latest test. You might have removed 
```
<!-- build:css -->
    ...
<!-- endbuild -->
```
comment tags ?

**Comment by aligajani** [comment]
I have. Try running your existing boilerplate setup. It won't work.

**Comment by henrikhb** [comment]
The `<!-- build:css/js -->` tags have to stay in the HTML.

I've just downloaded the repo fresh from Github and runned npm install.
When running "gulp" afterwards I get a "dist" folder with e.g. 
`<link rel="stylesheet" href="assets/css/main.min.css">` in the `<head>` tag.

**Comment by aligajani** [comment]
Can you do `gulp build` after `npm install`. I did the same thing as you, but did not get `.min*` files.

**Comment by henrikhb** [comment]
I see why you're not getting the .min files. `gulp build` is not actually meant to be runned on its own here. Use `gulp serve` for development and only `gulp` for build. I configured the default `gulp` command to be the full build, which includes the renaming of sources.
